ARG POSTGIS_VESRSION=latest
FROM mdillon/postgis:${POSTGIS_VESRSION}

# update and install the necessary requirement
RUN apt-get update -y
RUN apt install apt-utils -y
RUN apt-get upgrade -y
RUN apt-get install git -y
RUN git config --global http.sslVerify false
# install cart

RUN git clone  https://github.com/gravitystorm/openstreetmap-carto.git 
RUN cd openstreetmap-carto
RUN pwd
RUN ls -la ./openstreetmap-carto