version: '3.2'
services:
  potgis:
    restart: 'always'
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=osm"
    ports:
      - "5432:5432"
    build: './osm-client/'
  # ubuntu:
  #   restart: 'always'
  #   build: './osm-client/'
  #   container_name: 'Ubuntu-osm-client'
  #   ports:
  #     - "5432:5432"